CREATE TABLE IF NOT EXISTS `attributes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `charId` INT,
  `name` LONGTEXT NOT NULL,
  `age` INT,
  `height` INT,
  `details` LONGTEXT NOT NULL,
  `created` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;